### ISSUE TITLE
[NEW FEATURE] Add Transport HTTP 

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/phonebook-service#43]
## Issues
Create transport for access by http for accessing by client

## Tasks
- [x] add endpoint for health check
- [x] add http handler
- [x] update cmd/server/main.go
- [x] update Dockerfile
