### ISSUE TITLE
[NEW FEATURE] Create Check Healthy Liveness and Readiness

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/phonebook-service#52]
## Issue
Container's tech need health check for readiness and liveness of the API

## Tasks
 - [x] add healthy check for live
 - [x] add healthy check for ready
 - [x] add query for check db
