### ISSUE TITLE
[ENHANCEMENT] Create unit test for phonebook service and get coverage

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/phonebook-service#6]
## Task

- [x]  unit test for get list phonebook
- [x]  unit test for get detail phonebook
- [x]  unit test for insert new phonebook
- [x]  unit test for update a phonebook
- [x]  unit test for delete a phonebook
