### ISSUE TITLE
[BUGFIX] Fix response detail and get list of phonebook

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/phonebook-service#70]
## Issues
Response get list of phonebook should be static and resolve what client need

## Tasks
- [x] set some field into interface
- [x] add some field for using v1 contract API
- [x] fixed some query
